---
- name: Install dependencies
  become: "True"
  package:
    name:
      - curl
      - wget
      - lib32gcc1
      - lib32stdc++6
    state: present
    update_cache: "True"
    autoremove: "True"
    install_recommends: "True"

- name: Create Steam user
  become: "True"
  user:
    name: "{{ steamcmd_user }}"
    system: "True"
    create_home: "True"

- name: Create SteamCMD installation script folder
  become: "True"
  become_user: "{{ steamcmd_user }}"
  file:
    path: "{{ steamcmd_installation_folder }}"
    owner: "{{ steamcmd_user }}"
    group: "{{ steamcmd_user }}"
    mode: u=rwx,g=rwx,o=r
    state: directory

- name: Download and unarchive SteamCMD package
  become: "True"
  become_user: "{{ steamcmd_user }}"
  unarchive:
    src: "{{ steamcmd_download_link }}"
    dest: "{{ steamcmd_installation_folder }}"
    owner: "{{ steamcmd_user }}"
    group: "{{ steamcmd_user }}"
    mode: u=rwx,g=rwx,o=r
    remote_src: "True"
  args:
    creates: "{{ steamcmd_installation_folder }}/steamcmd.sh"

- name: Login SteamCMD
  become: "True"
  become_user: "{{ steamcmd_user }}"
  command: "{{ steamcmd_command }} +login {{ steamcmd_login_user }} {{ steamcmd_login_pass }} +quit"
  register: install_result
  ignore_errors: "True"
  args:
    chdir: "{{ steamcmd_installation_folder }}"
    creates: "{{ steamcmd_installation_folder }}/package"

- name: Copy log files
  fetch:
    src: "{{ steamcmd_installation_folder }}/logs/{{ item }}"
    dest: /tmp/logs
  when: install_result.rc > 0
  with_items:
    - appinfo_log.txt
    - bootstrap_log.txt
    - configstore_log.txt
    - connection_log.txt
    - content_log.txt
    - remote_steamcmd.txt
    - shader_log.txt
    - stderr.txt

- name: Starting debug steps
  debug:
    msg: "debug: {{ steamcmd_debug }}"
  when: steamcmd_debug == 'True'

- name: Pack install folder
  become: "True"
  become_user: "{{ steamcmd_user }}"
  community.general.archive:
    path: "{{ steamcmd_installation_folder }}"
    dest: "{{ steamcmd_installation_folder }}_pack.tar.bz2"
    format: bz2
    owner: "{{ steamcmd_user }}"
    group: "{{ steamcmd_user }}"
    mode: u=rwx,g=rwx,o=rwx
  when: steamcmd_debug == 'True'

- name: Copy packed files
  become: "True"
  become_user: "{{ steamcmd_user }}"
  fetch:
    src: "{{ steamcmd_installation_folder }}_pack.tar.bz2"
    dest: tmp/files
  when: steamcmd_debug == 'True'
